# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
    backend "s3" {
        bucket = "terraform-multi-env-management"
        key = "./terraform.tfstate"
        region = "us-east-1"
        encrypt = "true"
    }
}
